exec-once = swww init; swww kill; swww init
exec-once = foot --server & foot
exec-once = doas ydotoold -p $XDG_RUNTIME_DIR/.ydotool_socket -P 777
exec-once = xrdb $XDG_CACHE_HOME/wal/colors.Xresources
