exec-once = wbg $XDG_DATA_HOME/catppuccin.png & waybar & kitty
monitor = ,1920x1080,auto,auto
xwayland {
	force_zero_scaling = true
}

general {
	layout = master
	cursor_inactive_timeout = 5
	gaps_in = 5
	gaps_out = 5
	border_size = 3
	col.active_border = rgb(cba6f7) rgb(313244) rgb(313244) rgb(cba6f7) 45deg
	col.inactive_border = rgb(313244)
}

decoration {
	rounding = 10
	drop_shadow = true
	shadow_range = 20
	col.shadow = rgb(3c4252)
	col.shadow_inactive = rgb(3c4252)
	blur {
		enabled = true
		size = 10
		passes = 3
	}
}

animations {
	enabled = true
	bezier = pace, 0.46, 1, 0.29, 0.99
	bezier = overshot, 0.13, 0.99, 0.29, 1.1
	bezier = md3_decel, 0.05, 0.7, 0.1, 1
	animation = windowsIn, 1, 6, md3_decel, slide
	animation = windowsOut, 1, 6, md3_decel, slide
	animation = windowsMove, 1, 6, md3_decel, slide
	animation = fade, 1, 10, md3_decel
	animation = workspaces, 1, 7, md3_decel, slide
	animation = specialWorkspace, 1, 8, md3_decel, slide
	animation = border, 0, 3, md3_decel
}

bind = SUPER, return, exec, kitty
bind = SUPER, B, exec, killall waybar || waybar
bind = SUPER, D, exec, wofi
bind = SUPER, W, exec, firefox
bind = SUPER, R, exec, kitty -e lf
bind = SUPER, M, exec, pulsemixer --toggle-mute
binde = SUPER, Minus, exec, pulsemixer --change-volume -5
binde = SUPER, Equal, exec, pulsemixer --change-volume +5
binde = SUPER SHIFT, Minus, exec, pulsemixer --change-volume -25
binde = SUPER SHIFT, Equal, exec, pulsemixer --change-volume +25
binde = SUPER, Q, killactive,
bind = SUPER, BackSpace, exit,
bind = SUPER, F, fullscreen,
bind = SUPER SHIFT, Space, togglefloating,

bind = SUPER, Space, layoutmsg, swapwithmaster
binde = SUPER SHIFT, K, layoutmsg, swapprev
binde = SUPER SHIFT, J, layoutmsg, swapnext
binde = SUPER, K, layoutmsg, cycleprev
binde = SUPER, J, layoutmsg, cyclenext

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = SUPER, Right, workspace, e+1
bind = SUPER, Left, workspace, e-1
binde = SUPER, H, resizeactive, -30 0
binde = SUPER, L, resizeactive, 30 0

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
