#!/bin/sh

for x in su chown find shutdown reboot mount umount; do
    alias $x="sudo $x"
done; unset x

alias cp="cp -v"
alias mv="mv -v"
alias rm="rm -vf"

alias diff="diff -s --color=auto"
alias grep="sudo grep --color=auto"
alias rg="grep -rn --exclude-dir=.git"
alias ls="ls -Fa --color=always --group-directories-first"

alias v="nvim"
alias sv="sudo nvim"
alias p="yay --mflags '--skippgpcheck'"
alias ka="killall"
alias sdn="shutdown -h now"

alias gst="git status -sb"
alias gd="git diff"
alias ga="git add"
alias gc="git commit --allow-empty-message -m ''"
alias gp="git push"

ll() { ls -lh --time-style="+%Y/%m/%d" $@ | grep -v "^total"; }
fd() { find ${2:-/} -name $1 2>/dev/null; }
ft() {
    find ${2:-/} -newermt "${1:-5} seconds ago" -type f \
    ! -path "/dev/*" ! -path "/sys/*" ! -path "/proc/*" 2>/dev/null
}