#!/bin/sh

ll() { \ls -Fahl --color=always --group-directories-first --time-style="+%Y/%m/%d" $@ | grep -v "^total"; }
rg() { doas grep --color=always --exclude-dir=.git --exclude-dir=.cache -nr $1 $2 2>/dev/null; }
fd() {
	set -- $(echo "$1" | sed "s|^^|/|; s|\.|[^/]|g") $2
	doas find ${2:-/} 2>/dev/null | grep --color=auto "$1"
}
fdt() { doas find / -type f -newermt "${1:-10} seconds ago" ! -path "/proc/*" ! -path "/sys/*" 2>/dev/null; }
lt() {
	x="$1"
	shift
	time (for x in $(seq $x); do
	$@ >/dev/null 2>&1
	done)
	unset x
}
txz() {
	[ -d "$1" ] && tar -c $1 | pv -s $(du -sb $1 | cut -f 1) | xz -9 >$1.txz
	[ -f "$1" ] && pv $1 | xz -9 >$1.xz
	echo "[1;31m$(du -s $1 | cut -f 1)[0m -> [1;32m$(du $1.*xz | cut -f 1)[0m"
	echo "[1;31m$(du -sh $1 | cut -f 1)[0m -> [1;32m$(du -h $1.*xz | cut -f 1)[0m"
}

for x in cut awk tr sed grep cat chown chmod shutdown reboot mount umount ln su cfdisk pacman; do
  alias $x="doas $x"
done; unset x

alias \
	ls="ls -Fa --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff -s --color=auto" \
	cp="doas cp -iv --preserve=ownership" \
	mv="doas mv -iv" \
	rm="doas rm -Iv" \
	sdn="shutdown -h now" \
	dash="dash -V" \
	dl="cd ~/Downloads" \
	ka="killall" \
	p="pacman" \
	v="nvim" \
	dv="doas nvim" \
	gst="git status -sb" \
	ga="git add" \
	gr="git rm" \
	gu="git restore --staged" \
	gc="git commit --allow-empty-message -m \"\"" \
	gp="git push"
