#!/bin/sh

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ":")"
export EDITOR="nvim"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

export LESSKEYIN="$XDG_CONFIG_HOME/less/lesskey"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/history"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"

export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export STARSHIP_CONFIG="$ZDOTDIR/starship.toml"

eval "$(dircolors)"
export MANROFFOPT="-c"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

[ "$(tty)" = "/dev/tty1" ] && startx
